# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "144c8f2921e5212cd7dc0db700501a90"
name = "MyOperator(Staging)"
application_url = "https://mo-cli.vercel.app"
embedded = false
handle = "MyOperatorStaging"

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-07"
  
[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# Learn more at
# https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes

scopes = "read_customers,write_customers,read_orders,write_orders,read_products,write_products"

[auth]
redirect_urls = ["https://my-operator.vercel.app" , "https://mo-cli.vercel.app/auth/callback" , "https://mo-cli.vercel.app"]

[pos]
embedded = false


